[package]
name = "fibonacci-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guest"
path = "src/lib.rs"

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zkwasm-rust-sdk = { git = "https://github.com/DelphinusLab/zkWasm-rust.git" }
wasm-bindgen = "0.2.83"